name: Build Executable with PyInstaller

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner (64-bit)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py || { echo 'PyInstaller failed'; exit 1; }  # Error logging

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/main.exe  # Path to the Windows executable
